<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>
<body>

<div id="div_0"></div>
<div id="div_1"></div>
<br>
<div id="div_2"></div>
<div id="div_3"></div>
<br>
<div id="div_4"></div>

<script type="text/javascript" src="c:\WebServers\home\localhost\www\my_test_file .js"></script>
<script type="text/javascript" >
var z=document.getElementById("div_4");
z.innerHTML=arr[2];
</script>
</body>
</html>
